apiVersion: v2
name: aws-load-balancer-controller
version: 1.14.1
description: AWS Load Balancer Controller for Kubernetes
type: application
appVersion: "v2.14.1"
home: https://github.com/aws/eks-charts
sources:
  - https://github.com/aws/eks-charts
maintainers:
  - name: AWS EKS
keywords:
  - aws
  - alb
  - nlb
  - load-balancer
  - ingress

dependencies:
  - name: aws-load-balancer-controller
    version: 1.14.1
    repository: "file://./charts/aws-load-balancer-controller-1.14.1.tgz"
