# Chart.yaml with wrapper/dependency structure
# This is the current configuration used by GitLab CI/CD
# Use this if you want to deploy with the dependency structure

apiVersion: v2
name: aws-load-balancer-controller
version: 1.17.0
description: AWS Load Balancer Controller for Kubernetes
type: application
appVersion: "v2.17.0"
home: https://github.com/aws/eks-charts
sources:
  - https://github.com/aws/eks-charts
maintainers:
  - name: AWS EKS
keywords:
  - aws
  - alb
  - nlb
  - load-balancer
  - ingress

dependencies:
  - name: aws-load-balancer-controller
    version: 1.17.0
    repository: "file://./charts/aws-load-balancer-controller-1.17.0.tgz"
