apiVersion: v2
name: metrics-server
version: 3.13.0
description: Metrics Server for Kubernetes
type: application
appVersion: "0.7.2"
home: https://github.com/kubernetes-sigs/metrics-server
sources:
  - https://github.com/kubernetes-sigs/metrics-server
maintainers:
  - name: Kubernetes SIGs
keywords:
  - metrics
  - monitoring
  - kubernetes
