{{- if .Values.serviceAccount.annotations }}
{{- $saName := "secrets-store-csi-driver-provider-aws" }}
{{- if (index .Values "secrets-store-csi-driver-provider-aws" "rbac" "serviceAccountName") }}
{{- $saName = (index .Values "secrets-store-csi-driver-provider-aws" "rbac" "serviceAccountName") }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
