apiVersion: v2
name: external-dns
version: 1.19.0
description: External DNS for Kubernetes
type: application
appVersion: "0.19.0"
home: https://github.com/kubernetes-sigs/external-dns
sources:
  - https://github.com/kubernetes-sigs/external-dns
maintainers:
  - name: Kubernetes SIGs
keywords:
  - external-dns
  - dns
  - route53
  - aws

dependencies:
  - name: external-dns
    version: 1.19.0
    repository: "file://./charts/external-dns-1.19.0.tgz"
