apiVersion: v2
name: ingress-nginx
version: 4.13.3
description: NGINX Ingress Controller for Kubernetes
type: application
appVersion: "1.12.0"
home: https://github.com/kubernetes/ingress-nginx
sources:
  - https://github.com/kubernetes/ingress-nginx
maintainers:
  - name: Kubernetes
keywords:
  - ingress
  - nginx
  - kubernetes

dependencies:
  - name: ingress-nginx
    version: 4.13.3
    repository: "file://./charts/ingress-nginx-4.13.3.tgz"
