apiVersion: v2
name: cluster-autoscaler
version: 9.52.1
description: Cluster Autoscaler for Kubernetes
type: application
appVersion: "1.31.0"
home: https://github.com/kubernetes/autoscaler
sources:
  - https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler
maintainers:
  - name: Kubernetes Autoscaler
keywords:
  - cluster
  - autoscaler
  - scaling
  - aws

dependencies:
  - name: cluster-autoscaler
    version: 9.52.1
    repository: "file://./charts/cluster-autoscaler-9.52.1.tgz"
