apiVersion: v2
name: external-secrets
version: 0.20.4
description: External Secrets Operator
type: application
appVersion: "v0.20.4"
home: https://external-secrets.io
sources:
  - https://github.com/external-secrets/external-secrets
maintainers:
  - name: External Secrets
keywords:
  - external-secrets
  - secrets
  - aws
  - secrets-manager

dependencies:
  - name: external-secrets
    version: 0.20.4
    repository: "file://./charts/external-secrets-0.20.4.tgz"
