apiVersion: v2
name: aws-efs-csi-driver
version: 3.2.4
description: AWS EFS CSI Driver for Kubernetes
type: application
appVersion: "v2.0.7"
home: https://github.com/kubernetes-sigs/aws-efs-csi-driver
sources:
  - https://github.com/kubernetes-sigs/aws-efs-csi-driver
maintainers:
  - name: Kubernetes SIGs
keywords:
  - aws
  - efs
  - csi
  - storage
