apiVersion: v1
kind: Service
metadata:
  name: aws-load-balancer-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
